package ca.vanier.departmentapi.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Data

@Entity  // Table
@Builder

public class Department {

    @Id    //primary key
    @GeneratedValue (strategy = GenerationType.AUTO)  // Autogenerated value for primary key attribute
    private Long departmentIdId;

    private String departmentName;
    private String departmentAddress;
    private String departmentCode;     
}
